// Split fonts by unicode-range so the browser downloads only the slices a page actually uses.
// Usage (from frontend/): npm run fonts:subset   -> rewrites public/fonts/* and src/styles/fonts.css
//
// - NanumSquareRound (assets/fonts/, not on Google Fonts): 2 slices per weight.
//   slice 0 = Latin, symbols, jamo and the 2,350 common Hangul of KS X 1001 (first screen needs only this)
//   slice 1 = every other code point in the font (rare Hangul, hanja), fetched only when shown
// - Gaegu: Fontsource already ships Google's ~89 slices per weight; copied as-is (pinned version).
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import subsetFont from 'subset-font'

const SRC = '../assets/fonts'
const OUT = 'public/fonts'
const CSS = 'src/styles/fonts.css'
const GAEGU = { version: '5.3.0', weights: [400, 700] }
const NANUM = [
  { weight: 400, file: 'NanumSquareRoundR.woff2' },
  { weight: 700, file: 'NanumSquareRoundB.woff2' },
  { weight: 800, file: 'NanumSquareRoundEB.woff2' },
]

/** Code points of slice 0: ASCII/Latin-1, punctuation, arrows, CJK symbols, jamo, fullwidth, KS X 1001 Hangul. */
function commonCodePoints() {
  const set = new Set()
  const add = (a, b) => { for (let c = a; c <= b; c++) set.add(c) }
  add(0x20, 0x7e); add(0xa0, 0xff); add(0x2000, 0x206f); add(0x2190, 0x21ff); add(0x2460, 0x24ff)
  add(0x25a0, 0x25ff); add(0x2600, 0x26ff); add(0x3000, 0x303f); add(0x3131, 0x318e); add(0xff01, 0xff5e)
  const euckr = new TextDecoder('euc-kr')
  for (let hi = 0xb0; hi <= 0xc8; hi++)
    for (let lo = 0xa1; lo <= 0xfe; lo++) {
      const ch = euckr.decode(new Uint8Array([hi, lo]))
      if (ch >= '가' && ch <= '힣') set.add(ch.codePointAt(0))
    }
  return set
}

/** [1, 2, 3, 7] -> "U+1-3,U+7" */
function toUnicodeRange(points) {
  const sorted = [...points].sort((a, b) => a - b)
  const parts = []
  for (let i = 0; i < sorted.length; i++) {
    let j = i
    while (j + 1 < sorted.length && sorted[j + 1] === sorted[j] + 1) j++
    const hex = (n) => n.toString(16)
    parts.push(i === j ? `U+${hex(sorted[i])}` : `U+${hex(sorted[i])}-${hex(sorted[j])}`)
    i = j
  }
  return parts.join(',')
}

const fromPoints = (points) => String.fromCodePoint(...points)

async function nanumFaces() {
  const common = commonCodePoints()
  const rare = new Set()
  for (let c = 0x80; c <= 0xffff; c++) if (!common.has(c) && (c < 0xd800 || c > 0xdfff)) rare.add(c)
  const slices = [common, rare]
  const faces = []
  for (const { weight, file } of NANUM) {
    const font = readFileSync(`${SRC}/${file}`)
    for (const [i, points] of slices.entries()) {
      const out = await subsetFont(font, fromPoints(points), { targetFormat: 'woff2' })
      const name = `nanumsquareround-${i}-${weight}.woff2`
      writeFileSync(`${OUT}/${name}`, out)
      console.log(name, `${(out.length / 1024).toFixed(1)}KB`)
      faces.push(face('NanumSquareRound', weight, name, toUnicodeRange(points)))
    }
  }
  return faces
}

async function gaeguFaces() {
  const base = `https://cdn.jsdelivr.net/npm/@fontsource/gaegu@${GAEGU.version}`
  const faces = []
  let total = 0
  for (const weight of GAEGU.weights) {
    const css = await (await fetch(`${base}/${weight}.css`)).text()
    for (const block of css.matchAll(/url\(\.\/files\/([^)]+\.woff2)\)[^;]*;\s*unicode-range:\s*([^;]+);/g)) {
      const [, file, range] = block
      const res = await fetch(`${base}/files/${file}`)
      if (!res.ok) throw new Error(`${file}: ${res.status}`)
      const buf = Buffer.from(await res.arrayBuffer())
      writeFileSync(`${OUT}/${file}`, buf)
      total += buf.length
      faces.push(face('Gaegu', weight, file, range.trim()))
    }
  }
  console.log(`gaegu ${faces.length} slices, ${(total / 1024).toFixed(0)}KB total`)
  return faces
}

function face(family, weight, file, range) {
  return `@font-face {
  font-family: "${family}";
  src: url("/fonts/${file}") format("woff2");
  font-weight: ${weight};
  font-display: swap;
  unicode-range: ${range};
}`
}

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })
const header = `/*
 * GENERATED by \`npm run fonts:subset\` (scripts/subset-fonts.mjs). Do not edit by hand.
 * Fonts are split by unicode-range; the browser downloads only slices used on the page (design.md "폰트").
 * NanumSquareRound: NAVER, OFL-1.1. Gaegu: Google Fonts via Fontsource ${GAEGU.version}, OFL-1.1. Licenses: public/licenses/.
 */`
const faces = [...(await nanumFaces()), ...(await gaeguFaces())]
writeFileSync(CSS, `${header}\n${faces.join('\n')}\n`)
console.log(`wrote ${CSS} (${faces.length} faces)`)
